global:
  smtp_smarthost:      'smtp.gmail.com:587'
  smtp_from:           'YOUR_GMAIL@gmail.com'
  smtp_auth_username:  'YOUR_GMAIL@gmail.com'
  smtp_auth_password:  'YOUR_16_CHAR_APP_PASSWORD'
  smtp_require_tls:    true

route:
  group_by:       ['alertname', 'severity']
  group_wait:     30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email-team'

  routes:
    - match:
        severity: critical
      receiver: 'email-team'
      repeat_interval: 15m

receivers:
  - name: 'email-team'
    email_configs:
      - to: 'YOUR_GMAIL@gmail.com'
        subject: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          --------------------------------------------------
          Alert:       {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity:    {{ .Labels.severity }}
          Fired at:    {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          {{ end }}
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal: ['alertname']
